-- Скрипт сгенерирован Devart dbForge Studio for Oracle, Версия 3.1.190.1
-- Домашняя страница продукта: http://www.devart.com/ru/dbforge/oracle/studio
-- Дата скрипта: 26.05.2012 20:35:02
-- Версия сервера: Oracle Database 10g Express Edition Release 10.2.0.1.0 - Production
-- Версия клиента: 

DROP SEQUENCE ROOT.SQ;
CREATE SEQUENCE ROOT.SQ
  START WITH 281
  INCREMENT BY 1;

DROP TABLE ROOT.POST;
CREATE TABLE ROOT.POST (
  ID NUMBER(7),
  NAME VARCHAR2(256 BYTE),
  CONSTRAINT POST_ID_PK PRIMARY KEY (ID))
TABLESPACE USERS
STORAGE (
  INITIAL 64K
  MAXEXTENTS UNLIMITED
)
LOGGING;

DROP TABLE ROOT.CATEGORY;
CREATE TABLE ROOT.CATEGORY (
  ID NUMBER(7),
  NAME VARCHAR2(256 BYTE),
  CONSTRAINT CATEGORY_ID_PK PRIMARY KEY (ID))
TABLESPACE USERS
STORAGE (
  INITIAL 64K
  MAXEXTENTS UNLIMITED
)
LOGGING;

DROP TABLE ROOT.MAGAZINE;
CREATE TABLE ROOT.MAGAZINE (
  ID NUMBER(7),
  NAME VARCHAR2(256 BYTE),
  START_DATE DATE,
  COUNT_MAG NUMBER(7),
  COUNT_PAGE NUMBER(7),
  COMM VARCHAR2(2000 BYTE),
  CATEGORY_ID NUMBER(7),
  CONSTRAINT MAGAZINE_ID_PK PRIMARY KEY (ID),
  CONSTRAINT MAGAZINE_CATEGORY_ID_FK FOREIGN KEY (CATEGORY_ID)
    REFERENCES ROOT.CATEGORY(ID))
TABLESPACE USERS
STORAGE (
  INITIAL 64K
  MAXEXTENTS UNLIMITED
)
LOGGING;

DROP TABLE ROOT.WORKER;
CREATE TABLE ROOT.WORKER (
  ID NUMBER(7),
  NAME VARCHAR2(256 BYTE),
  POST_ID NUMBER(7),
  CONSTRAINT WORKER_ID_PK PRIMARY KEY (ID),
  CONSTRAINT WORKER_POST_ID_FK FOREIGN KEY (POST_ID)
    REFERENCES ROOT.POST(ID))
TABLESPACE USERS
STORAGE (
  INITIAL 64K
  MAXEXTENTS UNLIMITED
)
LOGGING;

DROP TABLE ROOT."RELEASE";
CREATE TABLE ROOT."RELEASE" (
  ID NUMBER(7),
  NAME VARCHAR2(256 BYTE),
  COMM VARCHAR2(2000 BYTE),
  MAGAZINE_ID NUMBER(7),
  START_DATE DATE,
  IMG_NAME VARCHAR2(256 BYTE),
  CONSTRAINT RELEASE_ID_PK PRIMARY KEY (ID),
  CONSTRAINT RELEASE_MAGAZINE_ID_FK FOREIGN KEY (MAGAZINE_ID)
    REFERENCES ROOT.MAGAZINE(ID))
TABLESPACE USERS
STORAGE (
  INITIAL 64K
  MAXEXTENTS UNLIMITED
)
LOGGING;

DROP TABLE ROOT.LIST_WORKERS;
CREATE TABLE ROOT.LIST_WORKERS (
  ID NUMBER(7),
  MAGAZINE_ID NUMBER(7),
  WORKER_ID NUMBER(7),
  SALARY NUMBER(7),
  CONSTRAINT LIST_WORKERS_ID_PK PRIMARY KEY (ID),
  CONSTRAINT LIST_WORKERS_MAGAZINE_ID_FK FOREIGN KEY (MAGAZINE_ID)
    REFERENCES ROOT.MAGAZINE(ID),
  CONSTRAINT LIST_WORKERS_WORKER_ID_FK FOREIGN KEY (WORKER_ID)
    REFERENCES ROOT.WORKER(ID))
TABLESPACE USERS
STORAGE (
  INITIAL 64K
  MAXEXTENTS UNLIMITED
)
LOGGING;